# version: '3'
services:
  fastbuka-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: fastbuka-api:1.0.0
    container_name: fastbuka-api
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    command: npm run start:prod
    depends_on:
      - db

  db:
    image: mongo:4.2
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  volumes:
    mongo-data: